### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by JonSim495** [phfbertoleti/ContadorObjetosEmMovimento#1]
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2729, in size
    return a.shape[axis]
AttributeError: 'NoneType' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 48, in <module>
    height = np.size(Frame,0)
  File "/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2731, in size
    return asarray(a).shape[axis]
IndexError: tuple index out of range

I receive this code when running in the virtual environment, can inform what is the problem?

**Comment by phfbertoleti** [comment]
Hi JonSim495.

It's odd. When I developed this project, I used Python 2.7 (and without virtual environment). I don't think the virtual environment can cause this, but different Python versions can. Please, try running this using Python 2.7 instead of 3.5.
