### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mathewspjacob** [phfbertoleti/ContadorObjetosEmMovimento#2]
Traceback (most recent call last):
  File "ContadorObjetosEmMovimento.py", line 50, in <module>
    height = np.size(Frame,0)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2700, in size
    return asarray(a).shape[axis]
IndexError: tuple index out of range

I'm using Python version 2.7.13 and Opencv version : 2.4.9.1

Can you please help me?

**Comment by mathewspjacob** [comment]
Hello, sit using this method how can I find total no of objects passed in the complete video?
